# Generated by Django 4.2.4 on 2023-09-18 22:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phonenumber', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=6)),
                ('married', models.BooleanField()),
                ('annaulincome', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coapplicantincome', models.IntegerField()),
                ('dependents', models.IntegerField()),
                ('education', models.CharField(max_length=15)),
                ('selfemployed', models.BooleanField()),
                ('credithistory', models.BooleanField()),
                ('propertyarea', models.CharField(max_length=10)),
                ('loanamount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('term', models.IntegerField()),
                ('predictedloanstatus', models.BooleanField()),
            ],
        ),
    ]
