# Generated by Django 4.2.4 on 2023-09-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanAnalysisApp', '0002_loan_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='predictedloanstatus',
            field=models.BooleanField(null=True),
        ),
    ]
