# Generated by Django 4.2.4 on 2023-09-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanAnalysisApp', '0003_alter_loan_predictedloanstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interest',
            field=models.IntegerField(),
        ),
    ]
