# Generated by Django 4.2.4 on 2023-09-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanAnalysisApp', '0004_alter_loan_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='id',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='unique_id',
        ),
        migrations.AlterField(
            model_name='loan',
            name='email',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
