# Generated by Django 4.2.4 on 2023-09-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanAnalysisApp', '0005_remove_loan_id_remove_loan_unique_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='downpayment',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='savingsbalance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
