# Generated by Django 4.2.4 on 2023-09-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanAnalysisApp', '0006_loan_downpayment_loan_savingsbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='emi',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
    ]
